=== nicolasrenet/segtformats/doc/seg_schema.json
{ 
  "id": "https://didip.uni-graz.at/segmentation.schema.json",
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$comment": "Created by NPR on 2026.02.06 - use the following: 'check-jsonschema --schemafile schema.json *.lines.gt.json' for CLI validation or 'jsonschema.validate(instance=dict, schema=dict)' for in-script validation.",
  "title": "Page Description",
  "description": "Line segmentation metadata schema, for DiDip/VRE internal use: structure of *.lines.{pred,gt}.json files.",
  "type": "object",
  "required": ["metadata", "image_filename", "image_width", "image_height","regions"],
  "properties": {
    "metadata": {
      "type": "object",
      "properties": {
        "created": { "type": "string" },
        "creator": { "type": "string" },
        "comment": { "type": "string" } },
      "required": ["created", "creator"] },
    "image_filename": { "type": "string" },
    "image_width": { "type": "integer" },
    "image_height": { "type": "integer" },
    "type": { "type": "string" },
    "text_direction": { "type": "string" },
    "lines": {"not":{}},
    "regions": {
      "type": "array",
      "items": {
        "type": "object",
        "required": ["id", "coords"],
        "properties": {
          "id": { "type": "string" },
          "coords": { "type": "array" }, 
          "regions": {"$ref": "#regions"},
          "lines": { 
            "type": "array",
            "items": {
              "type": "object", 
              "required": ["id", "coords", "baseline"],
              "properties": { 
                "id": { "type": "string" }, 
                "coords": { 
                  "type": "array",
                  "items": {
                    "type": "array",
                    "items": { "type": "integer" },
		    "minItems": 2,
		    "maxItems": 2 } }, 
                "x-height": { "type": "integer" },
                "centerline": { 
                  "type": "array",
                  "items": {
                    "type": "array",
                    "items": { "type": "integer" },
		    "minItems": 2,
		    "maxItems": 2 },
		  "minItems": 2 },
                "baseline": { 
                  "type": "array",
                  "items": {
                    "type": "array",
                    "items": { "type": "integer" },
		    "minItems": 2,
		    "maxItems": 2 },
		  "minItems": 2 } } } } } } } } }

=== nicolasrenet/segtformats/tests/data/4550c41616f9ef3a1a95a94155e67fe9.json
{ "metadata":
       {"created": "2025-11-07 13:42:10.346693",
    	"creator": "/home/nicolas/graz/htr/vre/ddpa_lines_ng/./bin/ddp_line_detect.py"
       },
    "image_filename": "4550c41616f9ef3a1a95a94155e67fe9.img.jpg",
    "image_width": 4955,
    "image_height": 3392,
    "regions": [
        {
            "id": "r0",
            "type": "text_region",
            "coords": [
                [
                    2448,
                    2106
                ],
                [
                    3127,
                    2106
                ],
                [
                    3127,
                    2258
                ],
                [
                    2448,
                    2258
                ]
            ],
            "lines": [
                {
                    "id": "l0",
                    "coords": [
                        [
                            2476,
                            2201
                        ],
                        [
                            2993,
                            2201
                        ],
                        [
                            3019,
                            2206
                        ],
                        [
                            3086,
                            2207
                        ],
                        [
                            3086,
                            2181
                        ],
                        [
                            3019,
                            2180
                        ],
                        [
                            2993,
                            2175
                        ],
                        [
                            2476,
                            2175
                        ]
                    ],
                    "baseline": [
                        [
                            2476,
                            2198
                        ],
                        [
                            2993,
                            2198
                        ],
                        [
                            3019,
                            2203
                        ],
                        [
                            3086,
                            2204
                        ]
                    ],
                    "height": 21,
                    "centerline": [
                        [
                            2476,
                            2188
                        ],
                        [
                            2993,
                            2188
                        ],
                        [
                            3019,
                            2193
                        ],
                        [
                            3086,
                            2194
                        ]
                    ]
                }
            ]
        },
        {
            "id": "r1",
            "type": "text_region",
            "coords": [
                [
                    2471,
                    605
                ],
                [
                    3777,
                    605
                ],
                [
                    3777,
                    2211
                ],
                [
                    2471,
                    2211
                ]
            ],
            "lines": [
                {
                    "id": "l0",
                    "coords": [
                        [
                            2498,
                            723
                        ],
                        [
                            3311,
                            729
                        ],
                        [
                            3472,
                            738
                        ],
                        [
                            3751,
                            739
                        ],
                        [
                            3751,
                            709
                        ],
                        [
                            3472,
                            708
                        ],
                        [
                            3311,
                            699
                        ],
                        [
                            2498,
                            693
                        ]
                    ],
                    "baseline": [
                        [
                            2498,
                            720
                        ],
                        [
                            3311,
                            726
                        ],
                        [
                            3472,
                            735
                        ],
                        [
                            3751,
                            736
                        ]
                    ],
                    "height": 24,
                    "centerline": [
                        [
                            2498,
                            708
                        ],
                        [
                            3311,
                            714
                        ],
                        [
                            3472,
                            723
                        ],
                        [
                            3751,
                            724
                        ]
                    ]
                },
                {
                    "id": "l1",
                    "coords": [
                        [
                            2508,
                            783
                        ],
                        [
                            2968,
                            798
                        ],
                        [
                            3490,
                            801
                        ],
                        [
                            3698,
                            816
                        ],
                        [
                            3698,
                            784
                        ],
                        [
                            3490,
                            769
                        ],
                        [
                            2968,
                            766
                        ],
                        [
                            2508,
                            751
                        ]
                    ],
                    "baseline": [
                        [
                            2508,
                            780
                        ],
                        [
                            2968,
                            795
                        ],
                        [
                            3490,
                            798
                        ],
                        [
                            3698,
                            813
                        ]
                    ],
                    "height": 26,
                    "centerline": [
                        [
                            2508,
                            767
                        ],
                        [
                            2968,
                            782
                        ],
                        [
                            3490,
                            785
                        ],
                        [
                            3698,
                            800
                        ]
                    ]
                },
                {
                    "id": "l2",
                    "coords": [
                        [
                            2512,
                            850
                        ],
                        [
                            2583,
                            849
                        ],
                        [
                            2943,
                            863
                        ],
                        [
                            3472,
                            867
                        ],
                        [
                            3716,
                            885
                        ],
                        [
                            3716,
                            853
                        ],
                        [
                            3472,
                            835
                        ],
                        [
                            2943,
                            831
                        ],
                        [
                            2583,
                            817
                        ],
                        [
                            2512,
                            818
                        ]
                    ],
                    "baseline": [
                        [
                            2512,
                            846
                        ],
                        [
                            2583,
                            845
                        ],
                        [
                            2943,
                            859
                        ],
                        [
                            3472,
                            863
                        ],
                        [
                            3716,
                            881
                        ]
                    ],
                    "height": 25,
                    "centerline": [
                        [
                            2512,
                            834
                        ],
                        [
